// constants.js

const MESSAGE_VOLUMES = [
    '10', '100', '1000', '10000', '100000', 
    '250000', '500000', '750000', '1000000', 
    '5000000', '10000000+'
];

const OPT_IN_TYPES = [
    'VERBAL', 'WEB_FORM', 'PAPER_FORM', 'VIA_TEXT', 'MOBILE_QR_CODE'
];

const USE_CASE_CATEGORIES = [
    'TWO_FACTOR_AUTHENTICATION',
    'ACCOUNT_NOTIFICATIONS',
    'CUSTOMER_CARE',
    'CHARITY_NONPROFIT',
    'DELIVERY_NOTIFICATIONS',
    'FRAUD_ALERT_MESSAGING',
    'EVENTS',
    'HIGHER_EDUCATION',
    'K12',
    'MARKETING',
    'POLLING_AND_VOTING_NON_POLITICAL',
    'POLITICAL_ELECTION_CAMPAIGNS',
    'PUBLIC_SERVICE_ANNOUNCEMENT',
    'SECURITY_ALERT'
];

module.exports = {
    MESSAGE_VOLUMES,
    OPT_IN_TYPES,
    USE_CASE_CATEGORIES
};
